apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1  # 메모리 절약을 위해 일단 1개만 띄웁니다.
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account-service
        # [중요] 사용자님의 ECR 이미지 주소로 확인하세요!
        image: 549027855245.dkr.ecr.ap-northeast-2.amazonaws.com/fin-prod-account:latest
        ports:
        - containerPort: 5000  # 파이썬 Flask 앱이 사용하는 포트
        resources:
          limits:
            memory: "128Mi"  # [보안/운영 팁] t3.micro를 위해 메모리를 제한합니다.
          requests:
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: LoadBalancer  # 외부에서 접속할 수 있게 로드밸런서를 생성합니다.
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80         # 외부에서 접속할 포트
      targetPort: 5000 # 컨테이너 내부 포트